#!/bin/bash
# Copyright (C) 2011-2013 OpenStack Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

# dib-lint: disable=set setu setpipefail indent
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e

case "$DIB_INIT_SYSTEM" in
    systemd)
        glean_path_dib="/etc/systemd/system/glean@.service.d"
        mkdir -p $glean_path_dib
        nodepool_base="$(dirname $0)/../glean@.service.d"
        cp -RP $nodepool_base/override.conf $glean_path_dib/override.conf
        ;;
    *)
        echo "Skipping glean systemd configuration"
        ;;
esac
