#!/bin/bash
# Copyright (C) 2011-2013 OpenStack Foundation
# Copyright 2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# NOTE(pabelanger): Until zuulv3 lands, manually copy scripts / data into
# /usr/local/jenkins.
mkdir -p /usr/local/jenkins
cp -a /opt/git/openstack-infra/project-config/jenkins/data \
    /usr/local/jenkins/common_data
cp -a /opt/git/openstack-infra/project-config/jenkins/scripts \
    /usr/local/jenkins/slave_scripts
