- job-template:
    name: '{pipeline}-requirements-integration-dsvm{variant}'
    node: '{node}'

    wrappers:
      - build-timeout:
          timeout: 125
      - timestamps

    builders:
      - link-logs
      - net-info
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=120
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_EXERCISES=0
          export DEVSTACK_GATE_REQS_INTEGRATION=1
          export PIP_PROCESS_DEPENDENCY_LINKS=1
          if [ "{variant}" = "-resolver" ]; then
              export PBR_PIP_VERSION=git+https://github.com/rbtcollins/pip.git@issue-988#egg=pip
          fi
          function gate_hook {{
              set -x
              bash $BASE/new/devstack-gate/devstack-vm-gate.sh && \
              bash -xe $BASE/new/requirements/tools/integration.sh $(cat $BASE/new/requirements/projects.txt)
          }}
          export -f gate_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

    publishers:
      - devstack-logs
      - console-log

- job-template:
    name: '{pipeline}-pbr-installation-dsvm{variant}'
    node: '{node}'

    wrappers:
      - build-timeout:
          timeout: 125
      - timestamps

    builders:
      - link-logs
      - net-info
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=120
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_EXERCISES=0
          export DEVSTACK_GATE_REQS_INTEGRATION=1
          export PIP_PROCESS_DEPENDENCY_LINKS=1
          if [ "{variant}" = "-upstream" ]; then
              export PBR_PIP_VERSION=git+https://github.com/pypa/pip.git@develop#egg=pip
          fi
          function gate_hook {{
              set -x
              bash -xe $BASE/new/pbr/tools/integration.sh $(cat $BASE/new/requirements/projects.txt)
          }}
          export -f gate_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

    publishers:
      - devstack-logs
      - console-log

- job:
    name: propose-requirements-updates
    node: proposal

    builders:
      - revoke-sudo
      - link-logs
      - net-info
      - gerrit-git-prep
      - shell: /usr/local/jenkins/slave_scripts/propose_update.sh requirements

    publishers:
      - console-log

- job-template:
    name: propose-requirements-constraints{branch-designator}
    node: proposal

    builders:
      - revoke-sudo
      - link-logs
      - net-info
      - branch-git-prep:
          branch: '{branch-override}'
      - shell: |
          /usr/local/jenkins/slave_scripts/propose_update.sh \
          requirements-constraints

    publishers:
      - console-log
