- name: Build Releasenotes
  hosts: all
  roles:
    - role: ensure-if-python
      # Releasenotes do not need the package itself to be installed
      install_package: false
    - build-releasenotes
