- name: Publish StarlingX Web Content
  hosts: localhost
  roles:
    - role: create-afs-token
      when: zuul_success | bool
    - role: upload-afs-roots
      afs_target: "/afs/.openstack.org/project/starlingx.io/www{{ afs_subpath | default('') }}"
      when: zuul_success | bool
    - role: destroy-afs-token
      when: zuul_success | bool
