#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DIB_INIT_SYSTEM" in
    upstart)
        # nothing to do
        exit 0
        ;;
    systemd)
        # stick with default systemd timesyncd on focal and beyond
        if [[ ":focal: :jammy:" =~ :${DIB_RELEASE}: ]]; then
            exit 0
        elif [[ $DISTRO_NAME = "ubuntu" || $DISTRO_NAME = "debian" ]]; then
            systemctl enable ntp.service
        elif [[ ( $DISTRO_NAME == "centos" && $DIB_RELEASE > 7 ) || $DISTRO_NAME == "fedora" || $DISTRO_NAME == "rocky" ]]; then
            systemctl enable chronyd
        else
            systemctl enable ntpd.service
        fi
        ;;
    openrc)
        rc-update add ntp-client default
        rc-update add acpid default
        ;;
    sysv)
        # ntp is enabled by default, nothing to do
        exit 0
        ;;
    *)
        echo "Unsupported init system $DIB_INIT_SYSTEM"
        exit 1
        ;;
esac
