#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DIB_INIT_SYSTEM" in
    upstart)
        # nothing to do
        exit 0
        ;;
    systemd)
        if [[ $DISTRO_NAME = "ubuntu" || $DISTRO_NAME = "debian" ]]; then
            systemctl enable ntp.service
        else
            systemctl enable ntpd.service
        fi
        ;;
    openrc)
        rc-update add ntp-client default
        rc-update add acpid default
        ;;
    sysv)
        # ntp is enabled by default, nothing to do
        exit 0
        ;;
    *)
        echo "Unsupported init system $DIB_INIT_SYSTEM"
        exit 1
        ;;
esac
