dashboard:
  title: Networking ODL Failure Rate
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](https://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://opendev.org/openstack/project-config/src/grafana/networking-odl.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Tests Failure Rates (Check queue)
          span: 4
          yaxes:
            - label: Failure rates %
              format: percent
            - show: false
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.openstack-tox-py27.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.openstack-tox-py27.{SUCCESS,FAILURE})),'24hours'), 'openstack-tox-py27')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.openstack-tox-py35.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.openstack-tox-py35.{SUCCESS,FAILURE})),'24hours'), 'openstack-tox-py35')
          type: graph
        - title: Unit Tests Failure Rates (Gate queue)
          span: 4
          yaxes:
            - label: Failure rates %
              format: percent
            - show: false
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_networking-odl.master.job.openstack-tox-py27.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_networking-odl.master.job.openstack-tox-py27.{SUCCESS,FAILURE})),'24hours'), 'openstack-tox-py27')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_networking-odl.master.job.openstack-tox-py35.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_networking-odl.master.job.openstack-tox-py35.{SUCCESS,FAILURE})),'24hours'), 'openstack-tox-py35')
          type: graph
        - title: Grenade Tests Failure Rates (Check queue)
          span: 4
          yaxes:
            - label: Failure rates %
              format: percent
            - show: false
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-grenade.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-grenade.{SUCCESS,FAILURE})),'24hours'), 'networking-odl-grenade')
          type: graph
        - title: Functional Tests Failure Rates (Check queue)
          span: 4
          yaxes:
            - label: Failure rates %
              format: percent
            - show: false
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-functional-oxygen.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-functional-oxygen.{SUCCESS,FAILURE})),'24hours'), 'networking-odl-functional-oxygen')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-functional-fluorine.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-functional-fluorine.{SUCCESS,FAILURE})),'24hours'), 'networking-odl-functional-fluorine')
          type: graph
        - title: Functional Tests Failure Rates (Gate queue)
          span: 4
          yaxes:
            - label: Failure rates %
              format: percent
            - show: false
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-functional-oxygen.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-functional-oxygen.{SUCCESS,FAILURE})),'24hours'), 'networking-odl-functional-oxygen')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-functional-fluorine.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-functional-oxygen.{SUCCESS,FAILURE})),'24hours'), 'networking-odl-functional-fluorine')
          type: graph
        - title: Tempest Failure Rates (Check queue)
          span: 4
          yaxes:
            - label: Failure rates %
              format: percent
            - show: false
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-tempest-oxygen.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-tempest-oxygen.{SUCCESS,FAILURE})),'24hours'), 'networking-odl-tempest-oxygen')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-tempest-fluorine.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-tempest-fluorine.{SUCCESS,FAILURE})),'24hours'), 'networking-odl-tempest-fluorine')
          type: graph
        - title: Multi-node Failure Rates (Check queue)
          span: 4
          yaxes:
            - label: Failure rates %
              format: percent
            - show: false
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-tempest-oxygen-multinode.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-tempest-oxygen-multinode.{SUCCESS,FAILURE})),'24hours'), 'networking-odl-tempest-oxygen-multinode')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-tempest-fluorine-multinode.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-tempest-fluorine-multinode.{SUCCESS,FAILURE})),'24hours'), 'networking-odl-tempest-fluorine-multinode')
          type: graph
        - title: Rally Failure Rates (Check queue)
          span: 4
          yaxes:
            - label: Failure rates %
              format: percent
            - show: false
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-rally-oxygen.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-rally-oxygen.{SUCCESS,FAILURE})),'24hours'), 'networking-odl-rally-oxygen')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-rally-fluorine.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_networking-odl.master.job.networking-odl-rally-fluorine.{SUCCESS,FAILURE})),'24hours'), 'networking-odl-rally-fluorine')
          type: graph
        - title: Periodic jobs
          span: 4
          yaxes:
            - label: Failure rates %
              format: percent
            - show: false
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.periodic.project.opendev_org.openstack_networking-odl.master.job.legacy-periodic-py35-with-neutron-lib-master.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.periodic.project.opendev_org.openstack_networking-odl.master.job.legacy-periodic-py35-with-neutron-lib-master.{SUCCESS,FAILURE})),'24hours'), 'legacy-periodic-py35-with-neutron-lib-master')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.periodic-stable.project.opendev_org.openstack_networking-odl.stable_pike.job.build-openstack-sphinx-docs.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.periodic-stable.project.opendev_org.openstack_networking-odl.stable_pike.job.build-openstack-sphinx-docs.{SUCCESS,FAILURE})),'24hours'), 'build-openstack-sphinx-docs-pike')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.periodic-stable.project.opendev_org.openstack_networking-odl.stable_pike.job.openstack-tox-py27.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.periodic-stable.project.opendev_org.openstack_networking-odl.stable_pike.job.openstack-tox-py27.{SUCCESS,FAILURE})),'24hours'), 'openstack-tox-py27-pike')
          type: graph
