{
 "title": "Nodepool: DIB Status",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dib_image",
    "query": "stats.timers.nodepool.dib_image_build.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Build Status Overview",
   "type": "heatmap-new",
   "description": "This shows the Unix return status of the build for each image type.  Values may be a bit weird if the buckets merge together, but a non-zero value indicates an error",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.nodepool.dib_image_build.*.status.rc, 4)"
    }
   ]
  },
  {
   "title": "$dib_image status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "dib_image",
   "targets": [
    {}
   ]
  },
  {
   "title": "Build status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.nodepool.dib_image_build.$dib_image.status.rc"
    }
   ]
  },
  {
   "title": "Image size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.nodepool.dib_image_build.$dib_image.*.size, 5)"
    }
   ]
  },
  {
   "title": "Build duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(keepLastValue(stats.timers.nodepool.dib_image_build.$dib_image.status.duration.mean), 'Time')"
    }
   ]
  },
  {
   "title": "Last build",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(stats.gauges.nodepool.dib_image_build.$dib_image.status.last_build, 1000)"
    }
   ]
  }
 ]
}