{
 "title": "Zuul Launcher: Rackspace-Flex",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "Rackspace-Flex Zuul-Launcher Status\n========================\n\nThis dashboard monitors the status of Zuul Launcher in Rackspace-Flex.\n\n**This dashboard is managed by [Grafyaml](https://docs.openstack.org/infra/system-config/grafyaml.html).**\nIf you would like to make changes to this dashboard, please see the template in the `grafana` directory in\n[project-config](https://opendev.org/openstack/project-config/src/branch/master/grafana/zuul-launcher-ir.template).\n"
   }
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Requested",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers_$region-main.nodes.state.requested)"
    }
   ]
  },
  {
   "title": "Building",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers-$region-main.nodes.state.building)"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers-$region-main.nodes.state.ready)"
    }
   ]
  },
  {
   "title": "In Use",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers-$region-main.nodes.state.in-use)"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Resources - $region",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "repeat": "region",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers-$region-main.usage.instances, 'Instances')"
    },
    {
     "target": "alias(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers-$region-main.limit.instances, 'instance limit')"
    },
    {
     "target": "alias(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers-$region-main.usage.ram, 'RAM')"
    },
    {
     "target": "alias(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers-$region-main.limit.ram, 'ram limit')"
    }
   ]
  },
  { "title": "Test Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Test Node History - $region",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "repeat": "region",
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers-$region-main.nodes.state.building), 'Building')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers-$region-main.nodes.state.ready), 'Ready')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers-$region-main.nodes.state.in-use), 'In Use')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers-$region-main.nodes.state.used), 'Used')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers-$region-main.nodes.state.requested), 'Requested')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.zuul.provider.opendev_org2Fopendev2Fzuul-providers-$region-main.limit.instances), 'Max')"
    }
   ]
  }
 ]
}