dashboard:
  title: Zuul Load Balancer
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](https://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://opendev.org/openstack/project-config/src/grafana/zuul-loadbalancer.yaml).
          type: text
    - title: HTTPS Frontend
      showTitle: true
      height: 250px
      panels:
        - title: HTTPS Frontend Connection Rate
          span: 6
          targets:
            - target: alias(stats.haproxy.balance_zuul_https.FRONTEND.stot, 'Connections/sec')
          type: graph
        - title: HTTPS Frontend Input/Output Rate
          span: 6
          targets:
            - target: alias(scale(stats.haproxy.balance_zuul_https.FRONTEND.bin,8), 'Received bits/sec')
            - target: alias(scale(stats.haproxy.balance_zuul_https.FRONTEND.bout,8), 'Transmitted bits/sec')
          type: graph
        - title: HTTPS Frontend Current Sessions
          span: 6
          targets:
            - target: alias(stats.gauges.haproxy.balance_zuul_https.FRONTEND.scur, 'Sessions')
          type: graph
        - title: HTTPS Frontend Request Error Rate
          span: 6
          targets:
            - target: alias(stats.haproxy.balance_zuul_https.FRONTEND.ereq, 'Errors/sec')
          type: graph
    - title: HTTPS Servers
      showTitle: true
      height: 250px
      panels:
        - title: HTTPS Server Connection Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_https.*.opendev.org.stot, 3)
          type: graph
        - title: HTTPS Server Input Rate
          span: 3
          targets:
            - target: aliasByNode(scale(stats.haproxy.balance_zuul_https.*.opendev.org.bin,8), 3)
          type: graph
        - title: HTTPS Server Output Rate
          span: 3
          targets:
            - target: aliasByNode(scale(stats.haproxy.balance_zuul_https.*.opendev.org.bout,8), 3)
          type: graph
        - title: HTTPS Frontend Current Sessions
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_https.*.opendev.org.scur, 4)
          type: graph
        - title: HTTPS Server Connection Error Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_https.*.opendev.org.econ, 3)
          type: graph
        - title: HTTPS Server Response Error Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_https.*.opendev.org.eresp, 3)
          type: graph
        - title: HTTPS Server Connection Retry Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_https.*.opendev.org.wretr, 3)
          type: graph
        - title: HTTPS Server Connection Redispatch Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_https.*.opendev.org.wredis, 3)
          type: graph
        - title: HTTPS Server Average Queue Time
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_https.*.opendev.org.qtime, 4)
          type: graph
        - title: HTTPS Server Average Connect Time
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_https.*.opendev.org.ctime, 4)
          type: graph
        - title: HTTPS Server Average Response Time
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_https.*.opendev.org.rtime, 4)
          type: graph
        - title: HTTPS Server Average Session Time
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_https.*.opendev.org.ttime, 4)
          type: graph
    - title: HTTP Frontend
      showTitle: true
      height: 250px
      panels:
        - title: HTTP Frontend Connection Rate
          span: 6
          targets:
            - target: alias(stats.haproxy.balance_zuul_http.FRONTEND.stot, 'Connections/sec')
          type: graph
        - title: HTTP Frontend Input/Output Rate
          span: 6
          targets:
            - target: alias(scale(stats.haproxy.balance_zuul_http.FRONTEND.bin,8), 'Received bits/sec')
            - target: alias(scale(stats.haproxy.balance_zuul_http.FRONTEND.bout,8), 'Transmitted bits/sec')
          type: graph
        - title: HTTP Frontend Current Sessions
          span: 6
          targets:
            - target: alias(stats.gauges.haproxy.balance_zuul_http.FRONTEND.scur, 'Sessions')
          type: graph
        - title: HTTP Frontend Request Error Rate
          span: 6
          targets:
            - target: alias(stats.haproxy.balance_zuul_http.FRONTEND.ereq, 'Errors/sec')
          type: graph
    - title: HTTP Servers
      showTitle: true
      height: 250px
      panels:
        - title: HTTP Server Connection Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_http.*.opendev.org.stot, 3)
          type: graph
        - title: HTTP Server Input Rate
          span: 3
          targets:
            - target: aliasByNode(scale(stats.haproxy.balance_zuul_http.*.opendev.org.bin,8), 3)
          type: graph
        - title: HTTP Server Output Rate
          span: 3
          targets:
            - target: aliasByNode(scale(stats.haproxy.balance_zuul_http.*.opendev.org.bout,8), 3)
          type: graph
        - title: HTTP Frontend Current Sessions
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_http.*.opendev.org.scur, 4)
          type: graph
        - title: HTTP Server Connection Error Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_http.*.opendev.org.econ, 3)
          type: graph
        - title: HTTP Server Response Error Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_http.*.opendev.org.eresp, 3)
          type: graph
        - title: HTTP Server Connection Retry Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_http.*.opendev.org.wretr, 3)
          type: graph
        - title: HTTP Server Connection Redispatch Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_http.*.opendev.org.wredis, 3)
          type: graph
        - title: HTTP Server Average Queue Time
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_http.*.opendev.org.qtime, 4)
          type: graph
        - title: HTTP Server Average Connect Time
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_http.*.opendev.org.ctime, 4)
          type: graph
        - title: HTTP Server Average Response Time
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_http.*.opendev.org.rtime, 4)
          type: graph
        - title: HTTP Server Average Session Time
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_http.*.opendev.org.ttime, 4)
          type: graph
    - title: Finger Frontend
      showTitle: true
      height: 250px
      panels:
        - title: Finger Frontend Connection Rate
          span: 6
          targets:
            - target: alias(stats.haproxy.balance_zuul_finger.FRONTEND.stot, 'Connections/sec')
          type: graph
        - title: Finger Frontend Input/Output Rate
          span: 6
          targets:
            - target: alias(scale(stats.haproxy.balance_zuul_finger.FRONTEND.bin,8), 'Received bits/sec')
            - target: alias(scale(stats.haproxy.balance_zuul_finger.FRONTEND.bout,8), 'Transmitted bits/sec')
          type: graph
        - title: Finger Frontend Current Sessions
          span: 6
          targets:
            - target: alias(stats.gauges.haproxy.balance_zuul_finger.FRONTEND.scur, 'Sessions')
          type: graph
        - title: Finger Frontend Request Error Rate
          span: 6
          targets:
            - target: alias(stats.haproxy.balance_zuul_finger.FRONTEND.ereq, 'Errors/sec')
          type: graph
    - title: Finger Servers
      showTitle: true
      height: 250px
      panels:
        - title: Finger Server Connection Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_finger.*.opendev.org.stot, 3)
          type: graph
        - title: Finger Server Input Rate
          span: 3
          targets:
            - target: aliasByNode(scale(stats.haproxy.balance_zuul_finger.*.opendev.org.bin,8), 3)
          type: graph
        - title: Finger Server Output Rate
          span: 3
          targets:
            - target: aliasByNode(scale(stats.haproxy.balance_zuul_finger.*.opendev.org.bout,8), 3)
          type: graph
        - title: Finger Frontend Current Sessions
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_finger.*.opendev.org.scur, 4)
          type: graph
        - title: Finger Server Connection Error Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_finger.*.opendev.org.econ, 3)
          type: graph
        - title: Finger Server Response Error Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_finger.*.opendev.org.eresp, 3)
          type: graph
        - title: Finger Server Connection Retry Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_finger.*.opendev.org.wretr, 3)
          type: graph
        - title: Finger Server Connection Redispatch Rate
          span: 3
          targets:
            - target: aliasByNode(stats.haproxy.balance_zuul_finger.*.opendev.org.wredis, 3)
          type: graph
        - title: Finger Server Average Queue Time
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_finger.*.opendev.org.qtime, 4)
          type: graph
        - title: Finger Server Average Connect Time
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_finger.*.opendev.org.ctime, 4)
          type: graph
        - title: Finger Server Average Response Time
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_finger.*.opendev.org.rtime, 4)
          type: graph
        - title: Finger Server Average Session Time
          span: 3
          targets:
            - target: aliasByNode(stats.gauges.haproxy.balance_zuul_finger.*.opendev.org.ttime, 4)
          type: graph
