- name: Check Release Approvals
  hosts: localhost
  roles:
    - role: check-release-approval
      change: "{{ zuul.change }}"
      releases: "{{ zuul.executor.work_root }}/{{ zuul.project.src_dir }}"
      governance: "{{ zuul.executor.work_root }}/{{ zuul.projects['opendev.org/openstack/governance'].src_dir }}"
