#!/bin/bash
# Copyright (C) 2011-2013 OpenStack Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

# Remove additional sources used to install puppet or special version of pypi.
# We do this because leaving these sources in place causes every test that
# does an apt-get update to hit those servers which may not have the uptime
# of our local mirrors.

# dib-lint: disable=sete setu setpipefail
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e

OS_FAMILY=$(facter osfamily)

case $OS_FAMILY in
    "Debian")
        repo=/etc/apt/sources.list.d/puppetlabs.list
        update="apt-get update"
        ;;
    "RedHat")
        repo=/etc/yum.repos.d/puppetlabs.repo
        # yum/dnf will notice this is gone, so don't need to spend
        # time updating.
        update=""
        ;;
    "Gentoo")
        # make a fake repo to satisfy the removal below
        touch /tmp/fakerepo
        repo=/tmp/fakerepo
        update=""
        ;;
    "Suse")
        repo=/etc/zypp/repos.d/systemsmanagement_puppet.repo
        update=""
        ;;
    *)
        die "Don't know how to cleanup!"
        ;;
esac

rm -f $repo
$update

rm /usr/local/bin/prepare-node
