#!/bin/bash
# Copyright (C) 2015 OpenStack Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# Install bindep into a virtualenv
# This is in /usr instead of /usr/local due to this bug on precise:
# https://bugs.launchpad.net/ubuntu/+source/python2.7/+bug/839588

# dib-lint: disable=setu setpipefail
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e

python3 -m venv /usr/bindep-env
if [[ ${DIB_RELEASE} == 'xenial' ]]; then
    # The pip on xenial can't figure out it shouldn't install
    # the latest pip; this is the last to support 3.5
    /usr/bindep-env/bin/pip install --upgrade pip==20.3.4
else
    /usr/bindep-env/bin/pip install --upgrade pip
fi
/usr/bindep-env/bin/pip install bindep
