#!/bin/bash
# Copyright (C) 2011-2015 OpenStack Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

# dib-lint: disable=setu setpipefail
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e

if [[ ${YUM:-yum} == "dnf" ]]; then
    echo "*** caching disabled for dnf"
    echo "*** see https://etherpad.openstack.org/p/infra-f22"
    exit 0
fi

# Build up a list of packages to install by concatenating bindep lists
FALLBACKREPO=/opt/git/openstack-infra/project-config
FALLBACKFILE=jenkins/data/bindep-fallback.txt
PACKAGES=`git --git-dir=$FALLBACKREPO/.git show master:$FALLBACKFILE`
REQSFILE=other-requirements.txt
for REPO in /opt/git/*/* ; do
    BRANCHES=`git --git-dir=$REPO/.git branch -r | grep '^  origin/[^H]'`
    for BRANCH in $BRANCHES ; do
        REQS=`git --git-dir=$REPO/.git show $BRANCH:$REQSFILE 2>/dev/null \
            || true`
        if [ -n "$REQS" ] ; then
            PACKAGES=`echo -e "$PACKAGES\n$REQS" | sort -u`
        fi
    done
done
# TODO(fungi) once https://review.openstack.org/195201 appears in a bindep
# release, replace the next four lines with:
# PACKAGELIST=`echo "$PACKAGES" | /usr/bindep-env/bin/bindep -b -f - || true`
PACKAGESFILE=`mktemp`
echo "$PACKAGES" > $PACKAGESFILE
PACKAGELIST=`/usr/bindep-env/bin/bindep -b -f $PACKAGESFILE || true`
rm $PACKAGESFILE

if [ -f /usr/bin/apt-get ] ; then
    # --ignore-missing conflicts with set -e, so force it to be ok
    apt-get -y --ignore-missing -d install $PACKAGELIST || true
else
    yum install -y --downloadonly $PACKAGELIST
fi
