- hosts: all
  roles:
    - fetch-javascript-output
    - version-from-git
    - fetch-javascript-tarball

- hosts: all
  tasks:
    # project_ver is set by set_fact in version-from-git, but that runs on
    # the remote host, which puts the fact into the hostvars of that host.
    # Now that we're running on localhost, we need to reach in to the remote
    # hosts vars to get the value.
    - block:
        - name: Upload to npm
          include_role:
            name: upload-npm
      delegate_to: localhost
