- name: Fetch Javascript Artifacts for Publication
  hosts: all
  roles:
    - fetch-javascript-output
    - version-from-git
    - fetch-javascript-tarball

- name: Publish Javascript Artifacts to NPM
  hosts: all
  tasks:
    # project_ver is set by set_fact in version-from-git, but that runs on
    # the remote host, which puts the fact into the hostvars of that host.
    # Now that we're running on localhost, we need to reach in to the remote
    # hosts vars to get the value.
    - name: Upload to NPM
      delegate_to: localhost
      block:
        - name: Upload to npm
          include_role:
            name: upload-npm
