#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Put a timestamp in the image file of the date the image was built.
# This is echoed into the logs on each run for easy cross-reference

date --utc "+%Y-%m-%d %H:%M" > /etc/dib-builddate.txt
