#!/bin/bash
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.

# dib-lint: disable=setu setpipefail
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e

if [[ $DISTRO_NAME != "fedora" && $DIB_RELEASE != "24" ]]; then
    echo "Skipping Fedora 24 workaround"
    exit 0
fi

# This kernel has a single OVS patch
#  https://git.kernel.org/cgit/linux/kernel/git/davem/net.git/commit/?id=5ef9f289c4e698054e5687edb54f0da3cdc9173a
# to enable F24 testing until we get a fixed official kernel released
dnf -y copr enable iwienand/kernel-f24-rhbz1361414

# Current Fedora dib does a cleanup of the kernels to only leave the
# latest kernel around (for size purposes).  That means this
# effectively races with the upstream kernel to see who is the latest;
# when upstream updates, this kernel will be second and get kicked out
# in cleanup until we rebuild a new version.

# This patch has been added to the F24 kernel repo, however, so we can
# remove it once the next stable point release is cut
#   http://pkgs.fedoraproject.org/cgit/rpms/kernel.git/commit/?h=f24&id=c3c83b942761d78d9b362dbd3fdec4112d099b87

dnf -y update
