#!/bin/bash
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.

# dib-lint: disable=setu setpipefail
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e

if [[ $DISTRO_NAME != "fedora" && $DIB_RELEASE != "24" ]]; then
    echo "Skipping Fedora 24 workaround"
    exit 0
fi

# This kernel has a single OVS patch
#  https://git.kernel.org/cgit/linux/kernel/git/davem/net.git/commit/?id=5ef9f289c4e698054e5687edb54f0da3cdc9173a
# to enable F24 testing until we get a fixed official kernel released
dnf -y copr enable iwienand/kernel-4.6.4-301.rhbz1361414
dnf update -y

# This seems something like the least-worse way to do things ...
#  https://fedoraproject.org/wiki/GRUB_2#Setting_default_entry
echo "GRUB_DEFAULT=saved" >> /etc/default/grub
echo "GRUB_SAVEDEFAULT=false" >> /etc/default/grub
grub2-set-default 'Advanced options for Fedora 24 (Twenty Four)>Fedora (4.6.4-301.rhbz1361414.fc24.x86_64) 24 (Twenty Four)'
