- name: Run propose_update.sh Script
  hosts: all
  tasks:
    - name: Run propose_update.sh script
      vars:
        proposal_env:
          PCU_FILE: "{{ pcu_file | default('test-requirements.txt') }}"
          PCU_PACKAGES: "{{ (pcu_packages | default([])) | join(' ') }}"
      command: "{{ ansible_user_dir }}/scripts/propose_update.sh {{ update_target }} {{ zuul.branch }}"
      args:
        chdir: "src/{{ zuul.project.canonical_name }}"
      environment: '{{ zuul | zuul_legacy_vars | ansible.builtin.combine(proposal_env) }}'
