- name: Propose Constraints Update
  hosts: all
  tasks:

    - name: Propose constraints update
      command: "./tools/propose_projects_yaml_update.sh"
      args:
        chdir: "src/{{ zuul.project.canonical_name }}"
