#!/bin/bash
# Copyright (C) 2011-2013 OpenStack Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

if [ -f /usr/bin/yum ] ; then
    # --downloadonly is provided by the yum-plugin-downloadonly
    # package which is a virtual package in newer releases but an
    # optional package in older ones such as CentOS/RHEL 6.x, so
    # install it just to be sure it will work
    yum install -y yum-plugin-downloadonly
fi

while read line ; do

    if [ -f /usr/bin/apt-get ] ; then
        # --ignore-missing conflicts with set -e, so force it to be ok
        apt-get -y --ignore-missing -d install $line || true
    else
        yum install -y --downloadonly $line
    fi

done < /tmp/pkgs-to-install

rm /tmp/pkgs-to-install
