#!/bin/bash
# Copyright (C) 2011-2013 OpenStack Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

if grep "^CentOS release 6" /etc/redhat-release ; then
    # --downloadonly is provided by the yum-plugin-downloadonly package on
    # CentOS 6.x
    CENTOS6=1
    yum install -y yum-plugin-downloadonly
else
    CENTOS6=0
fi

while read line ; do

    if [ -f /usr/bin/apt-get ] ; then
        # --ignore-missing conflicts with set -e, so force it to be ok
        apt-get -y --ignore-missing -d install $line || true
    else
        if [ $CENTOS6 -eq 1 ] ; then
            # some packages may depend on python-setuptools, which is not
            # installed and cannot be reinstalled on CentOS 6.x once yum
            # has erased them, so use --skip-broken to avoid aborting; also
            # on this platform --downloadonly causes yum to return nonzero
            # even when it succeeds, so ignore its exit code
            yum install -y --downloadonly --skip-broken $line || true
        else
            yum install -y --downloadonly $line
        fi
    fi

done < /tmp/pkgs-to-install

rm /tmp/pkgs-to-install
