#!/bin/bash
# Copyright (C) 2014 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

# dib-lint: disable=setpipefail
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu

TEMPEST_DIR=/opt/git/openstack/tempest

# Setup venv and Install python deps from pip
sudo virtualenv /opt/git/subunit2sql-env
sudo -H /opt/git/subunit2sql-env/bin/pip install -U subunit2sql testrepository PyMySQL

sudo env PATH=/opt/git/subunit2sql-env/bin:$PATH /opt/git/subunit2sql-env/bin/python /opt/nodepool-scripts/prepare_tempest_testrepository.py $TEMPEST_DIR

sudo chown -R jenkins:jenkins $TEMPEST_DIR/preseed-streams

# Delete the venv after the script
sudo rm -rf /opt/git/subunit2sql-env
